import { LanguageCode } from '../types';

export interface Translations {
  programs: string;
  dashboard: string;
  docs: string;
  apiConsole: string;
  openSource: string;
  donate: string;
  about: string;
  promptAnalyzer: string;
  aiTutor: string;
  agenticAi: string;
  searchPlaceholder: string;
  classroom: string;
  settings: string;
  profile: string;
  themeLight: string;
  themeDark: string;
  scholarTier: string;
  facultyTier: string;
  schoolsTier: string;
  teamsTier: string;
  enterpriseTier: string;
  welcomeBack: string;
  universalEducationHeading: string;
  universalEducationSub: string;
  exploreCatalog: string;
  launchAiTutor: string;
  totalXP: string;
  level: string;
  streak: string;
  badgesUnlocked: string;
  certificatesEarned: string;
  enrolledCourses: string;
  quickActions: string;
  architectCourse: string;
  inspectEngine: string;
  syncOffline: string;
  deepCrawlRag: string;
  conceptsThatClick: string;
  activeDiscovery: string;
  languageSettings: string;
  achievementsSystem: string;
  close: string;
  saveChanges: string;
}

export const LOCALIZATION_DICTIONARY: Record<LanguageCode, Translations> = {
  en: {
    programs: 'Degree Programs',
    dashboard: 'Dashboard',
    docs: 'Documentation',
    apiConsole: 'API Console',
    openSource: 'Open Source',
    donate: 'Donate',
    about: 'About Project',
    promptAnalyzer: 'Prompt Analyzer',
    aiTutor: 'Kudo Agent',
    agenticAi: 'Kudo Agent Engine',
    searchPlaceholder: 'Search degrees, courses, research, or docs...',
    classroom: 'Classroom',
    settings: 'Settings',
    profile: 'Profile & Credentials',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    scholarTier: 'Individual Scholar Tier',
    facultyTier: 'Faculty Teacher View',
    schoolsTier: 'Schools & Academies Tier',
    teamsTier: 'Corporate Teams Tier',
    enterpriseTier: 'Enterprise Global Tier',
    welcomeBack: 'Welcome back, Scholar',
    universalEducationHeading: 'Universal LMD Knowledge Without Paywalls',
    universalEducationSub: 'Accredited LMD degree pathways, Kudo Agent Socratic tutoring, and open-source intelligence for every learner on Earth.',
    exploreCatalog: 'Explore Degree Programs',
    launchAiTutor: 'Launch Kudo Agent',
    totalXP: 'Total Experience Points',
    level: 'Academic Level',
    streak: 'Daily Learning Streak',
    badgesUnlocked: 'Badges Unlocked',
    certificatesEarned: 'Verified Certificates',
    enrolledCourses: 'Active Enrolled Courses',
    quickActions: 'Executive Actions',
    architectCourse: 'Architect Adaptive Course',
    inspectEngine: 'Inspect Hybrid Engine',
    syncOffline: 'Toggle Offline Storage',
    deepCrawlRag: 'Deep Crawl Vector RAG',
    conceptsThatClick: 'Concepts That Click',
    activeDiscovery: 'Active Discovery',
    languageSettings: 'Language & Regional Settings',
    achievementsSystem: 'Badges, XP & Achievements Engine',
    close: 'Close',
    saveChanges: 'Save Changes',
  },
  es: {
    programs: 'Programas Universitarios',
    dashboard: 'Panel de Control',
    docs: 'Documentación',
    apiConsole: 'Consola de API',
    openSource: 'Código Abierto',
    donate: 'Donar',
    about: 'Acerca del Proyecto',
    promptAnalyzer: 'Analizador de Prompts',
    aiTutor: 'IA Agéntica',
    agenticAi: 'Motor de IA Agéntica',
    searchPlaceholder: 'Buscar títulos, cursos, investigaciones o documentos...',
    classroom: 'Google Classroom',
    settings: 'Configuración',
    profile: 'Perfil y Credenciales',
    themeLight: 'Modo Claro',
    themeDark: 'Modo Oscuro',
    scholarTier: 'Nivel Estudiante Individual',
    facultyTier: 'Vista de Docente',
    schoolsTier: 'Nivel Escuelas y Academias',
    teamsTier: 'Nivel Equipos Corporativos',
    enterpriseTier: 'Nivel Empresa Global',
    welcomeBack: 'Bienvenido de nuevo, Académico',
    universalEducationHeading: 'Conocimiento Universal Sin Muros de Pago',
    universalEducationSub: 'Rutas de grado LMD acreditadas, tutoría socrática con IA agéntica e inteligencia de código abierto para cada estudiante.',
    exploreCatalog: 'Explorar Programas de Grado',
    launchAiTutor: 'Iniciar IA Agéntica',
    totalXP: 'Puntos de Experiencia Totales',
    level: 'Nivel Académico',
    streak: 'Racha Diaria de Estudio',
    badgesUnlocked: 'Insignias Desbloqueadas',
    certificatesEarned: 'Certificados Verificados',
    enrolledCourses: 'Cursos Activos Inscritos',
    quickActions: 'Acciones Ejecutivas',
    architectCourse: 'Diseñar Curso con IA',
    inspectEngine: 'Inspeccionar Motor IA Híbrido',
    syncOffline: 'Alternar Almacenamiento Offline',
    deepCrawlRag: 'Búsqueda RAG Multimodal Profunda',
    conceptsThatClick: 'Conceptos que Encajan',
    activeDiscovery: 'Descubrimiento Activo',
    languageSettings: 'Configuración de Idioma y Región',
    achievementsSystem: 'Sistema de Insignias y Logros XP',
    close: 'Cerrar',
    saveChanges: 'Guardar Cambios',
  },
  fr: {
    programs: 'Programmes Diplômants',
    dashboard: 'Tableau de Bord',
    docs: 'Documentation',
    apiConsole: 'Console API',
    openSource: 'Open Source',
    donate: 'Faire un Don',
    about: 'À Propos',
    promptAnalyzer: 'Analyseur de Prompts',
    aiTutor: 'IA Agentique',
    agenticAi: 'Moteur IA Agentique',
    searchPlaceholder: 'Rechercher des diplômes, cours, recherches ou docs...',
    classroom: 'Google Classroom',
    settings: 'Paramètres',
    profile: 'Profil et Certificats',
    themeLight: 'Mode Clair',
    themeDark: 'Mode Sombre',
    scholarTier: 'Niveau Étudiant Individuel',
    facultyTier: 'Vue Enseignant / Faculté',
    schoolsTier: 'Niveau Écoles & Académies',
    teamsTier: 'Niveau Équipes Entreprises',
    enterpriseTier: 'Niveau Entreprise Mondiale',
    welcomeBack: 'Bon retour parmi nous, Chercheur',
    universalEducationHeading: 'Savoir Universel Sans Barrière Financière',
    universalEducationSub: 'Diplômes LMD accrédités, tutorat socratique par IA agentique et intelligence open source.',
    exploreCatalog: 'Explorer les Diplômes',
    launchAiTutor: 'Lancer l\'IA Agentique',
    totalXP: 'Points d\'Expérience Totaux',
    level: 'Niveau Académique',
    streak: 'Série d\'Étude Quotidienne',
    badgesUnlocked: 'Badges Débloqués',
    certificatesEarned: 'Certificats Vérifiés',
    enrolledCourses: 'Cours Enregistrés Actifs',
    quickActions: 'Actions Exécutives',
    architectCourse: 'Concevoir un Cours IA',
    inspectEngine: 'Inspecter le Moteur IA Hybride',
    syncOffline: 'Bascule Mode Hors-Ligne',
    deepCrawlRag: 'Recherche RAG Vectorielle',
    conceptsThatClick: 'Concepts Qui Déclenchent l\'Intuition',
    activeDiscovery: 'Découverte Active',
    languageSettings: 'Paramètres de Langue et Région',
    achievementsSystem: 'Système de Badges et Récompenses XP',
    close: 'Fermer',
    saveChanges: 'Enregistrer',
  },
  de: {
    programs: 'Studiengänge & Abschlüsse',
    dashboard: 'Dashboard',
    docs: 'Dokumentation',
    apiConsole: 'API Konsole',
    openSource: 'Open Source',
    donate: 'Spenden',
    about: 'Über das Projekt',
    promptAnalyzer: 'Prompt Analysator',
    aiTutor: 'Agentische KI',
    agenticAi: 'Agentische KI-Engine',
    searchPlaceholder: 'Abschlüsse, Kurse, Forschung oder Dokumente suchen...',
    classroom: 'Google Classroom',
    settings: 'Einstellungen',
    profile: 'Profil & Zertifikate',
    themeLight: 'Heller Modus',
    themeDark: 'Dunkler Modus',
    scholarTier: 'Einzelner Student',
    facultyTier: 'Dozenten-Ansicht',
    schoolsTier: 'Schulen & Akademien',
    teamsTier: 'Unternehmens-Teams',
    enterpriseTier: 'Globale Enterprise-Stufe',
    welcomeBack: 'Willkommen zurück, Akademiker',
    universalEducationHeading: 'Universelles Wissen ohne Bezahlschranken',
    universalEducationSub: 'Akkreditierte LMD-Abschlüsse, sokratische agentische KI-Tutorien und Open-Source-Intelligenz.',
    exploreCatalog: 'Studiengänge erkunden',
    launchAiTutor: 'Agentische KI starten',
    totalXP: 'Gesamte Erfahrungspunkte',
    level: 'Akademische Stufe',
    streak: 'Tägliche Lernserie',
    badgesUnlocked: 'Freigeschaltete Abzeichen',
    certificatesEarned: 'Verifizierte Zertifikate',
    enrolledCourses: 'Aktive Kurse',
    quickActions: 'Executive Aktionen',
    architectCourse: 'KI-Kurs erstellen',
    inspectEngine: 'Hybrid KI-Engine prüfen',
    syncOffline: 'Offline-Speicher umschalten',
    deepCrawlRag: 'Vektor RAG Tiefensuche',
    conceptsThatClick: 'Konzepte, die Klick machen',
    activeDiscovery: 'Aktive Entdeckung',
    languageSettings: 'Sprach- und Regionaleinstellungen',
    achievementsSystem: 'Abzeichen- & XP-Erfolgssystem',
    close: 'Schließen',
    saveChanges: 'Speichern',
  },
  ar: {
    programs: 'البرامج الأكاديمية والدرجات',
    dashboard: 'لوحة التحكم القيادية',
    docs: 'الوثائق العلمية',
    apiConsole: 'منصة البرمجيات API',
    openSource: 'المصدر المفتوح',
    donate: 'دعم المشروع',
    about: 'عن المبادرة',
    promptAnalyzer: 'محلل الأوامر الذكي',
    aiTutor: 'الذكاء الاصطناعي التفاعلي',
    agenticAi: 'محرك الذكاء الاصطناعي Agéntic',
    searchPlaceholder: 'ابحث عن البرامج والمساقات والمقالات العلمية...',
    classroom: 'الفصول الدراسية',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي والشهادات',
    themeLight: 'الوضع المضيء',
    themeDark: 'الوضع الليلي',
    scholarTier: 'مستوى الباحث المستقل',
    facultyTier: 'عرض أستاذ الجامعة',
    schoolsTier: 'مستوى المدارس والأكاديميات',
    teamsTier: 'مستوى فرق العمل',
    enterpriseTier: 'مستوى المؤسسات العالمية',
    welcomeBack: 'أهلاً بك مجدداً أيها الباحث',
    universalEducationHeading: 'المعرفة العالمية المتاحة للجميع مجاناً',
    universalEducationSub: 'مسارات دراسية جامعية معتمدة، تعليم سقراطي بالذكاء الاصطناعي، ومعرفة مفتوحة.',
    exploreCatalog: 'استكشف البرامج الجامعية',
    launchAiTutor: 'بدء الذكاء الاصطناعي Agéntic',
    totalXP: 'إجمالي نقاط الخبرة',
    level: 'المستوى الأكاديمي',
    streak: 'سلسلة التعلم اليومي',
    badgesUnlocked: 'الأوسمة المكتسبة',
    certificatesEarned: 'الشهادات المعتمدة',
    enrolledCourses: 'المساقات المفتوحة الحالية',
    quickActions: 'الإجراءات التنفيذية',
    architectCourse: 'تصميم مساق ذكي',
    inspectEngine: 'فحص محرك الذكاء الاصطناعي',
    syncOffline: 'مزامنة التخزين المحلي',
    deepCrawlRag: 'البحث الموجه المتعمق RAG',
    conceptsThatClick: 'مفاهيم راسخة تفاعلية',
    activeDiscovery: 'الاستكشاف النشط',
    languageSettings: 'إعدادات اللغة والمنطقة',
    achievementsSystem: 'منظومة الأوسمة ونقاط الإنجاز XP',
    close: 'إغلاق',
    saveChanges: 'حفظ التغييرات',
  },
  ja: {
    programs: '学位プログラム',
    dashboard: 'ダッシュボード',
    docs: 'ドキュメント',
    apiConsole: 'APIコンソール',
    openSource: 'オープンソース',
    donate: '寄付・支援',
    about: 'プロジェクト概要',
    promptAnalyzer: 'プロンプト解析',
    aiTutor: 'エージェンティックAI',
    agenticAi: 'エージェンティックAIエンジン',
    searchPlaceholder: '学位、コース、論文、ドキュメントを検索...',
    classroom: 'Google Classroom',
    settings: '設定',
    profile: 'プロフィールと修了証',
    themeLight: 'ライトモード',
    themeDark: 'ダークモード',
    scholarTier: '個人研究者プラン',
    facultyTier: '教員・教授ビュー',
    schoolsTier: '学校・アカデミープラン',
    teamsTier: '企業チームプラン',
    enterpriseTier: 'エンタープライズグローバル',
    welcomeBack: 'おかえりなさい、研究者様',
    universalEducationHeading: '学術障壁のない普遍的知識の開放',
    universalEducationSub: '認定LMD学位パス、エージェンティックAI対話型チュータリング、世界中の学習者のためのオープンソース知能。',
    exploreCatalog: '学位プログラムを探索',
    launchAiTutor: 'エージェンティックAIを起動',
    totalXP: '獲得経験値',
    level: '学術レベル',
    streak: '連続学習ストリーク',
    badgesUnlocked: '獲得バッジ',
    certificatesEarned: '検証済み修了証',
    enrolledCourses: '受講中のコース',
    quickActions: 'クイックアクション',
    architectCourse: 'AIコース構築',
    inspectEngine: 'ハイブリッドAIエンジン検査',
    syncOffline: 'オフライン同期切替',
    deepCrawlRag: '深層ベクトルRAG検索',
    conceptsThatClick: '直感で理解できる概念',
    activeDiscovery: 'アクティブ・ディスカバリー',
    languageSettings: '言語・地域設定',
    achievementsSystem: 'バッジ・XP実績システム',
    close: '閉じる',
    saveChanges: '変更を保存',
  },
  zh: {
    programs: '学位课程项目',
    dashboard: '控制台面板',
    docs: '学术文档',
    apiConsole: 'API 接口控制台',
    openSource: '开源社区',
    donate: '捐赠支持',
    about: '项目简介',
    promptAnalyzer: '提示词诊断器',
    aiTutor: '智能代理 AI',
    agenticAi: '智能代理 AI 引擎',
    searchPlaceholder: '搜索学位、课程、论文或文档...',
    classroom: '谷歌课堂集成',
    settings: '系统设置',
    profile: '个人档案与证书',
    themeLight: '日间明亮模式',
    themeDark: '夜间深色模式',
    scholarTier: '独立学者层级',
    facultyTier: '教师/教授视图',
    schoolsTier: '学校与学院层级',
    teamsTier: '企业团队层级',
    enterpriseTier: '全球企业级',
    welcomeBack: '欢迎回来，尊敬的学者',
    universalEducationHeading: '无付费墙的全人类普遍知识',
    universalEducationSub: '认证 LMD 学位路径、智能代理 AI 辅导，为全球每一位学习者提供开源智能。',
    exploreCatalog: '浏览学位项目',
    launchAiTutor: '启动智能代理 AI',
    totalXP: '总经验值',
    level: '学术等级',
    streak: '每日学习连胜',
    badgesUnlocked: '解锁勋章',
    certificatesEarned: '已验证证书',
    enrolledCourses: '正在学习课程',
    quickActions: '执行管理操作',
    architectCourse: 'AI 课程构建器',
    inspectEngine: '检查混合 AI 引擎',
    syncOffline: '离线存储同步',
    deepCrawlRag: '深度向量 RAG 检索',
    conceptsThatClick: '顿悟直觉概念',
    activeDiscovery: '主动式探索学习',
    languageSettings: '语言与区域设置',
    achievementsSystem: '勋章与 XP 成就系统',
    close: '关闭',
    saveChanges: '保存修改',
  },
  hi: {
    programs: 'डिग्री प्रोग्राम',
    dashboard: 'डैशबोर्ड',
    docs: 'दस्तावेज़',
    apiConsole: 'एपीआई कंसोल',
    openSource: 'ओपन सोर्स',
    donate: 'दान करें',
    about: 'परियोजना के बारे में',
    promptAnalyzer: 'प्राम्प्ट विश्लेषक',
    aiTutor: 'एजेंटिक एआई',
    agenticAi: 'एजेंटिक एआई इंजन',
    searchPlaceholder: 'डिग्री, पाठ्यक्रम, शोध या दस्तावेज़ खोजें...',
    classroom: 'गूगल क्लासरूम',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल और प्रमाण पत्र',
    themeLight: 'लाइट मोड',
    themeDark: 'डार्क मोड',
    scholarTier: 'व्यक्तिगत विद्वान स्तर',
    facultyTier: 'शिक्षक दृश्य',
    schoolsTier: 'विद्यालय और अकादमी स्तर',
    teamsTier: 'कॉर्पोरेट टीम स्तर',
    enterpriseTier: 'ग्लोबल एंटरप्राइज स्तर',
    welcomeBack: 'पुनः स्वागत है, विद्वान',
    universalEducationHeading: 'बिना किसी भुगतान के सार्वभौमिक ज्ञान',
    universalEducationSub: 'मान्यता प्राप्त एलएमडी डिग्री मार्ग, एजेंटिक एआई सुकरात शिक्षण, और खुला ज्ञान।',
    exploreCatalog: 'डिग्री प्रोग्राम देखें',
    launchAiTutor: 'एजेंटिक एआई शुरू करें',
    totalXP: 'कुल अनुभव अंक',
    level: 'अकादमिक स्तर',
    streak: 'दैनिक अध्ययन लकीर',
    badgesUnlocked: 'अनलॉक किए गए बैज',
    certificatesEarned: 'सत्यापित प्रमाण पत्र',
    enrolledCourses: 'सक्रिय पंजीकृत पाठ्यक्रम',
    quickActions: 'त्वरित कार्य',
    architectCourse: 'एआई कोर्स बनाएं',
    inspectEngine: 'हाइब्रिड एआई इंजन जांचें',
    syncOffline: 'ऑफ़लाइन संग्रहण टॉगल करें',
    deepCrawlRag: 'डीप क्रॉल वैक्टर RAG',
    conceptsThatClick: 'सटीक समझ की अवधारणाएं',
    activeDiscovery: 'सक्रिय खोज',
    languageSettings: 'भाषा और क्षेत्रीय सेटिंग्स',
    achievementsSystem: 'बैज और एक्सपी उपलब्धि प्रणाली',
    close: 'बंद करें',
    saveChanges: 'बदलाव सहेजें',
  }
};

export function getTranslation(lang: LanguageCode = 'en'): Translations {
  return LOCALIZATION_DICTIONARY[lang] || LOCALIZATION_DICTIONARY.en;
}
